### ISSUE TITLE
Build Environment instructions for wasm-pack leads to error

### ISSUE THREAD

**Issue by Charles-Johnson** [yewstack/docs#10]
When using `rollup` following the instructions found [here](https://yew.rs/docs/getting-started/build-environment), I get the following error in the command line:
```
$ rollup ./main.js --format iife --file ./pkg/bundle.js

./main.js → ./pkg/bundle.js...
[!] Error: Could not resolve entry module (./main.js).
Error: Could not resolve entry module (./main.js).
    at error (/Users/charlesjohnson/.nvm/versions/node/v10.15.3/lib/node_modules/rollup/dist/rollup.js:5363:30)
    at pluginDriver.hookFirst.then.resolveIdResult (/Users/charlesjohnson/.nvm/versions/node/v10.15.3/lib/node_modules/rollup/dist/rollup.js:12034:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
Before I that I ran `wasm-pack build` but it didn't produce a `main.js` file

**Comment by jstarry** [comment]
@kellytk do you mind looking into this?

**Comment by Charles-Johnson** [comment]
I was building the Sample App [here](https://yew.rs/docs/getting-started/build-a-sample-app). I just copied a pasted it to `src/lib.rs` and then edited the `Cargo.toml` to this:
```
[package]
name = "yew-app"
version = "0.1.0"
authors = ["Charles Johnson <charlesthomasjohnson0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = "0.10.0"

```

**Comment by Charles-Johnson** [comment]
I get a dead code warning when building with `wasm-pack`
```
$ wasm-pack build
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling yew-app v0.1.0 (/Users/charlesjohnson/yew-app)
warning: function is never used: `main`
  --> src/lib.rs:41:1
   |
41 | fn main() {
   | ^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

    Finished release [optimized] target(s) in 2.24s
⚠️   [WARN]: origin crate has no README
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 2.48s
[INFO]: 📦   Your wasm pkg is ready to publish at ./pkg.
```

**Comment by Charles-Johnson** [comment]
Can the Sample App only be built with `cargo-web`?

**Comment by kellytk** [comment]
@Charles-Johnson Would you try again with the instructions at https://github.com/yewstack/yew-wasm-pack-minimal and share your results?  I see a small difference with the command you're running (`wasm-pack build`) vs what I use. (`wasm-pack build --target web`)

**Comment by Charles-Johnson** [comment]
@kellytk I get the same error when running `wasm-pack build --target web` with the Sample App. I'll check out yew-wasm-pack-minimal

**Comment by Charles-Johnson** [comment]
I was able to build and serve https://github.com/yewstack/yew-wasm-pack-minimal

**Comment by kellytk** [comment]
@Charles-Johnson Would you be willing to isolate the divergence between the minimal example and the docs that's responsible for the error so the docs could be fixed?

**Comment by jstarry** [comment]
The sample app on the docs site is not compatible with `wasm-pack`
