### ISSUE TITLE
Error in one of pages about Properties

### ISSUE THREAD

**Issue by Mingun** [yewstack/docs#110]
Samples in https://yew.rs/docs/concepts/html/components has examples of creating properties struct:
```rust
#[derive(Properties)]
pub struct Props {
    pub children: Children,
}
...
#[derive(Properties)]
pub struct Props {
    pub children: ChildrenWithProps<ListItem>,
}
```

But https://yew.rs/docs/concepts/components/properties states, that `Props` struct must implement `Clone`. In one of there pages are error

**Comment by teymour-aldridge** [comment]
You're right - there should be an implementation of `Clone`.
Would you mind submitting a PR to fix this (just needs `#[derive(Properties, Clone)]` instead of `#[derive(Properties)]`)?

**Comment by Mingun** [comment]
Sure. #111
