### ISSUE TITLE
Build a Sample App code in the getting started section does not compile

### ISSUE THREAD

**Issue by tripokey** [yewstack/docs#16]
The code in the Build a Sample App page in the getting started section does not compile.

If the App struct is changed from:
`
struct App {
    clicked: bool,
    onclick: Callback<()>,
}
`

To (also updating the use yew:: to include ClickEvent):
`
struct App {
    clicked: bool,
    onclick: Callback<ClickEvent>,
}
`

The sample app compiles.

**Comment by jstarry** [comment]
Thanks, fixed!
