### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by mathiasrw** [yewstack/docs#50]
Hi

I just installed rust and did a 

    cargo install mdbook

but the build failed:

![billede](https://user-images.githubusercontent.com/1063454/77597357-e9b62b80-6efe-11ea-8c44-1348af05a0a5.png)

**Comment by jstarry** [comment]
Hey! What version of rust are you using? Looks like you'll need to update

**Comment by mathiasrw** [comment]
Oh gosh. You are right. 

![image](https://user-images.githubusercontent.com/1063454/77644378-30d50880-6f61-11ea-85d7-d94b8c3453b3.png)

I had installed rust in the command prior, so assumed that it was up to date. It must be a version I installed ages ago.

I'll figure it out.
