### ISSUE TITLE
Home page in chinese

### ISSUE THREAD

**Issue by victorhqc** [yewstack/docs#53]
I can't read the English homepage anymore because it changed to Chinese 😢 

<img width="1327" alt="Screenshot 2020-04-14 at 09 49 41" src="https://user-images.githubusercontent.com/726113/79199444-4d17e700-7e35-11ea-8f5e-dd74a687773c.png">

Was this [commit](https://github.com/yewstack/docs/commit/2069cd1298cd04366d88fdcd07a450fad8772c89) intended?

**Comment by jstarry** [comment]
Haha, not sure how that happened, thanks for making an issue, it's fixed!
