### ISSUE TITLE
Should explain how to build

### ISSUE THREAD

**Issue by ralfbiedert** [yewstack/docs#8]
I just wanted to implement a proposal for [this issue](https://github.com/yewstack/yew/issues/314)  but I had trouble building the documentation. Neither

- `mdbook serve` 
- `gitbook serve` 

ran out of the box from the top-level path. Then I gave up. It would be nice if there were a `BUILDING.md` or so (the `README.md` seems to be already Yew's main documentation) explaining how to build and serve this locally.

**Comment by jstarry** [comment]
Thanks for the issue @ralfbiedert, unfortunately gitbook doesn't have a great local development experience. I've enabled mdbook support but it's not super compatible
